title: MySpace Windows 93 Leaderboard
description: The ones with the most fwiends ğŸ…
theme: jekyll-theme-leap-day
show_downloads: true

date_format: "%Y-%m-%d %H:%M"

plugins:
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-sitemap
  
relative_links:
  enabled: true
  collections: true
