title: MySpace Windows 93 Leaderboard
description: The ones with the most fwiends ğŸ…
date_format: "%Y-%m-%d %H:%M"
theme: jekyll-theme-leap-day

plugins:
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-sitemap
  
relative_links:
  enabled: true
  collections: true
